name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build & Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Dependencies
        run: npm install

      - name: Typecheck
        run: npx tsc --noEmit

      - name: Test
        run: npm test

      - name: Verify Build
        run: npm run build